緯度と経度情報を post リクエストで投げて,json に保存
HARUKINEMA/ki-wi_API pull request #1
Opened 2021-11-26 03:57 UTC by SoyaUehara

2021-11-26 05:08 UTC, Issei0804-ie requested changes
修正お願いしますー

2021-11-26 05:08 UTC, Issei0804-ie commented on src/app.ts
> +router.get("/hello", (req: express.Request, res: express.Response) => {
使わないエンドポイントなんで消しちゃいましょう!!

2021-11-26 13:20 UTC, Issei0804-ie approved these changes
good!!

ただ、今は lat と lng を query から取ってるけど、できれば body から取る方法に変えたいですねー、今度やりましょう

2021-12-21 07:35 UTC, HARUKINEMA approved these changes

2021-12-21 07:35 UTC, merged